package com.ccy.lnb.en.greenDao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DISPLAY_MESS".
 */
@Entity
public class DisplayMess {
    private String sendTime;
    private String showTimeLong;
    private String message;

    @Id
    private Long id;

    @Generated
    public DisplayMess() {
    }

    public DisplayMess(Long id) {
        this.id = id;
    }

    @Generated
    public DisplayMess(String sendTime, String showTimeLong, String message, Long id) {
        this.sendTime = sendTime;
        this.showTimeLong = showTimeLong;
        this.message = message;
        this.id = id;
    }

    public String getSendTime() {
        return sendTime;
    }

    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    public String getShowTimeLong() {
        return showTimeLong;
    }

    public void setShowTimeLong(String showTimeLong) {
        this.showTimeLong = showTimeLong;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
