package com.ccy.lnb.en.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISPLAY_MESS".
*/
public class DisplayMessDao extends AbstractDao<DisplayMess, Long> {

    public static final String TABLENAME = "DISPLAY_MESS";

    /**
     * Properties of entity DisplayMess.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SendTime = new Property(0, String.class, "sendTime", false, "SEND_TIME");
        public final static Property ShowTimeLong = new Property(1, String.class, "showTimeLong", false, "SHOW_TIME_LONG");
        public final static Property Message = new Property(2, String.class, "message", false, "MESSAGE");
        public final static Property Id = new Property(3, Long.class, "id", true, "_id");
    }


    public DisplayMessDao(DaoConfig config) {
        super(config);
    }
    
    public DisplayMessDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISPLAY_MESS\" (" + //
                "\"SEND_TIME\" TEXT," + // 0: sendTime
                "\"SHOW_TIME_LONG\" TEXT," + // 1: showTimeLong
                "\"MESSAGE\" TEXT," + // 2: message
                "\"_id\" INTEGER PRIMARY KEY );"); // 3: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISPLAY_MESS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DisplayMess entity) {
        stmt.clearBindings();
 
        String sendTime = entity.getSendTime();
        if (sendTime != null) {
            stmt.bindString(1, sendTime);
        }
 
        String showTimeLong = entity.getShowTimeLong();
        if (showTimeLong != null) {
            stmt.bindString(2, showTimeLong);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(3, message);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DisplayMess entity) {
        stmt.clearBindings();
 
        String sendTime = entity.getSendTime();
        if (sendTime != null) {
            stmt.bindString(1, sendTime);
        }
 
        String showTimeLong = entity.getShowTimeLong();
        if (showTimeLong != null) {
            stmt.bindString(2, showTimeLong);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(3, message);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(4, id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3);
    }    

    @Override
    public DisplayMess readEntity(Cursor cursor, int offset) {
        DisplayMess entity = new DisplayMess( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // sendTime
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // showTimeLong
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // message
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DisplayMess entity, int offset) {
        entity.setSendTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setShowTimeLong(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMessage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DisplayMess entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DisplayMess entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DisplayMess entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
