package com.ccy.lnb.en.greenDao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MY_PHRASE".
 */
@Entity
public class MyPhrase {
    private String myMess;

    @Id
    private Long id;

    @Generated
    public MyPhrase() {
    }

    public MyPhrase(Long id) {
        this.id = id;
    }

    @Generated
    public MyPhrase(String myMess, Long id) {
        this.myMess = myMess;
        this.id = id;
    }

    public String getMyMess() {
        return myMess;
    }

    public void setMyMess(String myMess) {
        this.myMess = myMess;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
