package com.ccy.lnb.en.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_PHRASE".
*/
public class MyPhraseDao extends AbstractDao<MyPhrase, Long> {

    public static final String TABLENAME = "MY_PHRASE";

    /**
     * Properties of entity MyPhrase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MyMess = new Property(0, String.class, "myMess", false, "MY_MESS");
        public final static Property Id = new Property(1, Long.class, "id", true, "_id");
    }


    public MyPhraseDao(DaoConfig config) {
        super(config);
    }
    
    public MyPhraseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_PHRASE\" (" + //
                "\"MY_MESS\" TEXT," + // 0: myMess
                "\"_id\" INTEGER PRIMARY KEY );"); // 1: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_PHRASE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyPhrase entity) {
        stmt.clearBindings();
 
        String myMess = entity.getMyMess();
        if (myMess != null) {
            stmt.bindString(1, myMess);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyPhrase entity) {
        stmt.clearBindings();
 
        String myMess = entity.getMyMess();
        if (myMess != null) {
            stmt.bindString(1, myMess);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public MyPhrase readEntity(Cursor cursor, int offset) {
        MyPhrase entity = new MyPhrase( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // myMess
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyPhrase entity, int offset) {
        entity.setMyMess(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyPhrase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyPhrase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyPhrase entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
